[tasks.build-client]
description = "Build the React (or Vite) client"
command = "pnpm"
args = ["run", "build"]
cwd = "client"

[tasks.start-server]
description = "Start the Rocket server"
command = "cargo"
args = ["run"]

[tasks.start]
description = "Run both client and server"
run_task = { name = ["build-client", "start-server"], parallel = false }